In [9]:
#importar herramientas necesarias
#written by jorge orlando miranda ñahui
#uso de la función argmax para obtener los indices donde se presenta el mayor valor de un tensor
#uso de la operación tf.reduce_mean() para obtener la media aritmetica de un tensor
import numpy as np
import tensorflow as tf
import sys
#deshabilitar modo eager
tf.compat.v1.disable_eager_execution()
estate=tf.executing_eagerly()
if estate==False:
    print("EAGER DESACTIVADO")
else:
    print("EAGER ACTIVO , NO USAR SESIONES")


EAGER DESACTIVADO


In [19]:
#Usar el grafo por defecto y agregar operaciones
grafo=tf.compat.v1.get_default_graph()
with grafo.as_default() :
    #crar un tensor constante 
    c1=tf.constant(np.array([[10,10,10],
                             [3,20,15]]),dtype=tf.float32,name="c1")
    #uso de la función argmax, axis=0 , eje y <=> axis=0
    a0=tf.argmax(c1,axis=0) 
    #uso de la función argmax, axis=1 , eje x <=> axis=1
    a1=tf.argmax(c1,axis=1)
    #uso de la función argmax , axis=None
    aN=tf.argmax(c1)
    #uso de la función argmax , axis=-1 , ultimo eje, en este caso eje x <=> axis=1
    am1=tf.argmax(c1,axis=-1)
    #uso de la operación reduce_mean()
    media=tf.reduce_mean(c1,axis=None) # calcula la media de todos los elementos del tensor
    #crear lista de tensores
    l=[a0,a1,aN,am1]
    ls=[0,1,"None",-1]
with tf.compat.v1.Session() as sesion:
    #mostrar tensor de entrada
    print("============tENSOR DE ENTRADA ======")
    print(sesion.run(c1))
    #mostrar el resultado
    for a,b in zip(l,ls):
        print("======== RESULTADO ARGMAX axis= {} =============".format(b))
        print(sesion.run(a))
    #mostrar la media aritmetica del tensor
    print("Media aritmetica : ",sesion.run(media))

    

============tENSOR DE ENTRADA ======
[[10. 10. 10.]
 [ 3. 20. 15.]]
======== RESULTADO ARGMAX axis= 0 =============
[0 1 1]
======== RESULTADO ARGMAX axis= 1 =============
[0 1]
======== RESULTADO ARGMAX axis= None =============
[0 1 1]
======== RESULTADO ARGMAX axis= -1 =============
[0 1]
Media aritmetica :  11.333333
