In [45]:
%%html
<img src="braintels_TF.png" , width=500,height=500>

In [35]:
#importar herramientas necesarias
import numpy as np
import tensorflow as tf
#mostrar version
print(tf.__version__)
#deshabilitar el modo eager
tf.compat.v1.disable_eager_execution()
#verificar que el modo eager esta deshabilitado
print("¿MODO EAGER ACTIVADO ?",tf.executing_eagerly())

2.0.0
¿MODO EAGER ACTIVADO ? False


In [36]:
#input para el placeholder NxR (N => ejemplos ) (R => Entradas) 4 ejemplos y 2 entradas
Input=np.array([[0,1],[0.2,1.2],[-1,0.8],[0.6,0.9]])
#===========================Creación del grafo por defecto =============
#placeholder para la entrada
#========2x1===========
x=tf.compat.v1.placeholder(dtype=tf.float32,shape=(2,1),name="X")
#pesos sinapticos , se utilizara por ejemplos practicos el tensor constante
#===================3x2 ==================
w=tf.constant(np.random.randn(3,2),dtype=tf.float32,name="w")
#realizar el producto matricial entre x y w
#==============3x1===================
v=tf.matmul(w,x,name="v")
#utilizar la función softmax
#===============3x1==============0
y=tf.nn.softmax(v,axis=0,name="y")

In [44]:
#=========================Creación de la sesión para ejecutar el grafo===========
with tf.compat.v1.Session() as sesion:
    #para cada ejemplo de la entrada Input
    for i in range(4):
        #ejecutar y utilizar el feed_dict para el placeholder
        yval=sesion.run(y,feed_dict={x:Input[i,:].reshape(2,1)})
        #sumar la respuesta de cada neurona
        suma=np.sum(yval)
        print("==========================================================")
        print("Vector de Entrada de la red neuronal es: \n {}".format(Input[i,:].reshape(2,1)))
        print("Neuronas de salida en la iteración {} : \n  {}".format(i,yval))
        print("Suma de las respuesta de cada neurona de salida es:",np.round(suma))
        print("==========================================================")


Vector de Entrada de la red neuronal es: 
 [[0.]
 [1.]]
Neuronas de salida en la iteración 0 : 
  [[0.2783766 ]
 [0.18800662]
 [0.5336168 ]]
Suma de las respuesta de cada neurona de salida es: 1.0
Vector de Entrada de la red neuronal es: 
 [[0.2]
 [1.2]]
Neuronas de salida en la iteración 1 : 
  [[0.22467089]
 [0.17329861]
 [0.6020305 ]]
Suma de las respuesta de cada neurona de salida es: 1.0
Vector de Entrada de la red neuronal es: 
 [[-1. ]
 [ 0.8]]
Neuronas de salida en la iteración 2 : 
  [[0.5381413 ]
 [0.13662486]
 [0.32523376]]
Suma de las respuesta de cada neurona de salida es: 1.0
Vector de Entrada de la red neuronal es: 
 [[0.6]
 [0.9]]
Neuronas de salida en la iteración 3 : 
  [[0.17715415]
 [0.23460492]
 [0.588241  ]]
Suma de las respuesta de cada neurona de salida es: 1.0
